import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/Components/(Layout)/Header/Header";
import Footer from "@/Components/(Layout)/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Doc House",
  description: "Generated by next JS",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
