"use client";
import "./globals.css";

import { Montserrat, Roboto } from "next/font/google";
import AuthProvider from "./Authentication/AuthProvider/AuthProvider";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
});
const metadata = {
  title: "Doc House",
  description: "Generated by Next JS",
};
const queryClient = new QueryClient();
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={roboto.className}>
          <QueryClientProvider client={queryClient}>
            {children}
          </QueryClientProvider>
        </body>
      </AuthProvider>
    </html>
  );
}
