"use client";
import "./globals.css";

import { Lato, Roboto } from "next/font/google";
import AuthProvider from "./Authentication/AuthProvider/AuthProvider";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const roboto = Lato({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
});
const metadata = {
  title: "Doc House",
  description: "Generated by Next JS",
};
const queryClient = new QueryClient();
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <QueryClientProvider client={queryClient}>
          <body className={roboto.className}>{children}</body>
        </QueryClientProvider>
      </AuthProvider>
    </html>
  );
}
