import Contact from "@/Components/(Home)/Contact/Contact";
import Footer from "@/Components/(Home)/Footer/Footer";
import Header from "@/Components/(Home)/Header/Header";
import HeroSection from "@/Components/(Home)/HeroSection/HeroSection";
import Service from "@/Components/(Home)/Service/Service";
import Testimonial from "@/Components/(Home)/Testimonial/Testimonial";
export const metadata = {
  title: "Home | Doc House",
  description: "Generated by Next JS",
};

const Home = () => {
  return (
    <main>
      <Header />
      <HeroSection />
      <Service />
      <Contact />
      <Testimonial />
      <Footer />
    </main>
  );
};
export default Home;
