"use client";
import Footer from "@/Components/(Home)/Footer/Footer";
import Header from "@/Components/(Home)/Header/Header";
import React from "react";

export const metadata = {
  title: "Doctor | Doc House",
  description: "Generated by Next JS",
};
const page = () => {
  return (
    <div>
      <Header />
      <Footer />
    </div>
  );
};

export default page;
